### ISSUE TITLE
Checklist before making repo public

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/aquapointer#6]
Make a checklist before making repo public. This could include: 

- [x] add boilerplate with copyright info (similar to Mitiq's) to each file
- [X] check the information in the license is correct and up to date 
- [x] remove private documents
- [X] Enable setup.py #8 
- [x] Clean up code structure, https://github.com/unitaryfund/aquapointer/issues/2
- [x]  Add type hints and docstrings #5  and #19
- [x] Protect `main` branch

**Comment by Misty-W** [comment]
Repo is public as of today.
